### ISSUE TITLE
Add links to etherscan in the Pinboard tab

### ISSUE THREAD

**Issue by Alpha-Guy** [Octobay/app#30]
1. The depositor addresses should be linked to etherscan.
2. The "refund" button can be renamed to "withdraw", for the depositor.
3.  There needs to be a deposit button besides issues that are already present on the pinboard.
4. The link at the bottom of the page, points to the wrong OPIN token at present. 
5. Also, the link should open in a new tab. At present it opens in the same tab.

![Screenshot from 2020-12-30 10-36-57](https://user-images.githubusercontent.com/73331595/103331268-15b49d80-4a8b-11eb-96a0-52b3a6925dc2.png)

**Comment by mktcode** [comment]
Closed in favor of https://github.com/Octobay/app/issues/75 and https://github.com/Octobay/app/issues/76.
