### ISSUE TITLE
Design better logo

### ISSUE THREAD

**Issue by mktcode** [OctoBay/app#4]

**Comment by kavita121** [comment]
Hey!! I would like to help you :) Could you describe how would you like the logo to be

**Comment by mktcode** [comment]
Hey! Glad this project caught your attention and you'd like to help. Very much appreciated! :) I have to say though, that I'm not yet 100% sure about the name and therefore what the logo should be. Maybe we should have a chat in our discord server: https://discord.gg/DhKgHrFeCD :)
