### ISSUE TITLE
Get rid of contract addresses in .env

### ISSUE THREAD

**Issue by mktcode** [Octobay/app#88]
Currently the env vars `OCTOBAY_ADDRESS`, `OCTOBAY_GOVERNOR_ADDRESS`, `OCTOBAY_NFT_ADDRESS`, `GSN_PAYMASTER_ADDRESS` are used to initialize contracts in web3. These addresses should be pulled from our main Octobay contract.

**Comment by alo9507** [comment]
So you mean instead of being hardcoded they should be queried from the main Octobay contract on Kovan?

**Comment by mktcode** [comment]
Exactly. So that the only address we need to configure/change is the Octobay contract address.

**Comment by mktcode** [comment]
resolved in.... ehhh..... https://github.com/Octobay/app/commit/0157dc3eb8ae15e225f70209ad5d2b82cccab17a kind of.
But this issue can be closed. Things have changed anyway.
